/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.psvansluis.nahuatlnumbers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class NahuatlNumberTest {

    @Test
    void zeroReturnsAhtle() {
        NahuatlNumber a = new NahuatlNumber(0);
        assertEquals("ahtle", a.toClassical());
    }
}
