/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.psvansluis.nahuatlnumbers;

public class NahuatlNumber {
    private int val;
    private static final String COMBINER = "īpan";

    private enum BasicForms {
        ahtle(0, true),
        sē(1, true),
        sem(1, false),
        ōme(2, true),
        ōm(2, false),
        ēi(3, true),
        ē(3, false),;

        private int numericValue;
        private boolean wordFinal;

        BasicForms(int numericValue, boolean wordFinal) {
            this.numericValue = numericValue;
            this.wordFinal = wordFinal;
        }

        private static String get(int numericValue, boolean wordFinal) {
            for (BasicForms u : BasicForms.values()) {
                if (u.numericValue == numericValue && u.wordFinal == wordFinal) {
                    return u.name();
                }
            }
            return null;
        }
    }

    public NahuatlNumber(int val) {
        this.val = val;
    }

    public String toClassical() {
        return BasicForms.get(this.val, true);
    }

}
