/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.psvansluis.nahuatlnumbers;

public class NahuatlNumber {
    private int val;
    private static final String SMALLER_COMBINER = "on";
    private static final String LARGER_COMBINER = "īpan";
    private static final String FIVE_COMBINER = "chikᵂ";
    private static final char[] VOWELS = { 'a', 'e', 'i', 'o', 'ā', 'ē', 'ī', 'ō' };

    private enum BasicForms {
        ZERO(0, "ahtle"),
        ONE(1, "sē", "sen"),
        TWO(2, "ōme", "ōm"),
        THREE(3, "ēi"),
        FOUR(4, "nāwi"),
        FIVE(5, "mākᵂīlli"),
        TEN(10, "mahtlāktli"),
        FIFTEEN(15, "caxtōlli"),
        TWENTY(20, "pōwalli"),
        FOURHUNDRED(400, "tzontli"),
        EIGHTTHOUSAND(8000, "xiquipilli");

        private int numericValue;
        private String finalForm;
        private String combiningForm;

        BasicForms(int value, String finalForm) {
            this.numericValue = value;
            this.finalForm = finalForm;
            this.combiningForm = apocopate(finalForm);
        }

        BasicForms(int value, String finalForm, String combiningForm) {
            this.numericValue = value;
            this.finalForm = finalForm;
            this.combiningForm = combiningForm;
        }

        static String removeSuffix(String str, String suffix) {
            if (str.endsWith(suffix)) {
                str = str.substring(0, str.length() - 1);
            }
            return str;
        }

        private static String apocopate(String finalForm) {
            String out = removeSuffix(finalForm, "i");
            out = removeSuffix(out, "l");
            out = removeSuffix(out, "t");
            return out;
        }
    }

    public NahuatlNumber(int val) {
        this.val = val;
    }

    public String toClassical() {

    }

}
